### ISSUE TITLE
ProteinNet Questions

### ISSUE THREAD

**Issue by jonathanking** [memoryleak47/variadic-generics#3]
Hello,

I just wanted to point out that I may not be able to answer many of your questions about ProteinNet because I am not affiliated with the project. I do use ProteinNet regularly, however, and have developed an extension called [SidechainNet](https://github.com/jonathanking/sidechainnet) which makes it a bit easier to interface with the data if you are using Python. I thought I would bring this to your attention in case you were not aware.

Cheers!
Jonathan

**Comment by memoryleak47** [comment]
Uh, I think this message ended up in the wrong place.
Thanks for your help either way, I'll look into it!
